### ISSUE TITLE
ポートをparamにする

### ISSUE THREAD

**Issue by Nasupl** [open-rdc/futaba_servo#4]
ポートをparamとして設定できるようにする

**Comment by Nasupl** [comment]
#6 で対応

**Comment by DaikiMaekawa** [comment]
@Nasupl ttyUSB0以外になったらparamを毎回書き換えるの?

**Comment by Nasupl** [comment]
@DaikiMaekawa 
launchファイルから設定します．これまではハードコーディングでした．

**Comment by DaikiMaekawa** [comment]
@Nasupl udevルールを記述してデバイスIDを固定化するべきでは?

**Comment by Nasupl** [comment]
@DaikiMaekawa 
うーん，どうなんでしょうか．
RSC-U485を単一システムで複数使うことがないからといって，ノードで使用する内部的なポート名を固定してしまうというのはいまいちしっくり来ません．
RSC-U485はシステムからすればFT232にしか見えませんから，唯一のRSC-U485に対してudevルールを記述することはできても，全てのRSC-U485に対応するようなudevルールを記述することはできませ．なので，udevルールを作成して運用していこうとは思いますが，このレポジトリに含めることはないと思います．

**Comment by DaikiMaekawa** [comment]
なるほど、そういう方針でしたか。 それならば、launchファイルに引数を追加してポートを設定できるようにしたほうがいいと思います。 (デフォルト値はttyUSB0)
ユーザー側、例えばorne_navigation等からこのlaunchファイルをインクルードして任意のポートに書き換えることが可能になります。
